# Generated by Django 5.2.7 on 2026-01-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_exercises',
        ),
        migrations.DeleteModel(
            name='RecommendedExercise',
        ),
    ]
